python roofitCSV.py 0 0 
python roofitCSV.py 1 0 
python roofitCSV.py 2 0 
python roofitCSV.py 0 1 
python roofitCSV.py 1 1 
python roofitCSV.py 2 1 
python roofitCSV.py 0 2 
python roofitCSV.py 1 2 
python roofitCSV.py 2 2 
